### ISSUE TITLE
Refactoring: f"<var_name>" equivalent to just <var_name>

### ISSUE THREAD

**Issue by yoyonel** [poneoneo/Alibaba-CLI-Scrapper#10]
https://github.com/poneoneo/Alibaba-CLI-Scrapper/blob/9c7c45c6cd15c79fa965931bdbc2ecd176593ada/aba_cli_scrapper/html_to_disk.py#L12-L13

just write:
```python
 Path(folder_name).mkdir(exist_ok=True)
 return Path(folder_name)
```

by the way for this kind of `issue` (formatting code), i suggest to use tool like:
- [flake8](https://flake8.pycqa.org/en/latest/)
- [blake](https://black.readthedocs.io/en/stable/)

**Comment by poneoneo** [comment]
Actually I'm just running ruff vscode extension to fix linting errors and many stuff like that like import sorting.

**Comment by yoyonel** [comment]
Good idea [ruff](https://github.com/astral-sh/ruff) is a very good tool to use, i recommanded it :-)
Best (or better solution) it's to use this tool in [CI pipeline (*linter* step)](https://dev.to/ken_mwaura1/automate-python-linting-and-code-style-enforcement-with-ruff-and-github-actions-2kk1) and/or use it as [pre-commit hook](https://github.com/astral-sh/ruff-pre-commit) before/after push new commits in our repo !
If you need help, just tell me :-)

**Comment by poneoneo** [comment]
ofcourse CI pipeline will be the best option cause like you see sometime im forgot to run ruff on all files before to release a version. i'm actually learning how to implement CI pipeline in this project. means yes i need help to  deal with this and other stuff.
