### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by yoyonel** [poneoneo/Alibaba-CLI-Scrapper#11]
https://github.com/poneoneo/Alibaba-CLI-Scrapper/blob/9c7c45c6cd15c79fa965931bdbc2ecd176593ada/aba_cli_scrapper/scrape_from_disk.py#L52-L63

You don't really need a `Path` as argument here ... just a `str|Path|anything` that can be converted and used as a `Path` and `resolve` (in this, you just use the built-in `open` so a string is enough).

In Python (classical way), we don't really test the type of argument ... type casting is enough and we suppose that the API expose to user (the definition of function/class) is respected.

**Comment by poneoneo** [comment]
Ok it's very clear . So to resume if I decide to use path then i should  be logic to use Path related method to deal with file and if not then I should use python built-in method.

**Comment by yoyonel** [comment]
MmmMm not really what i said.
Your signature/defintion of `_retrieve_html_content_as_string(self, html_file: Path)` describe (optionnaly) the API for using this class member method.
The (dev) user HAS to respect this contract and in your implementation you're suppose that the contract is respected, you understand ?
However you can define a extended API to accept `str` instead of `Path` for this method ... 
What you want, just don't (i think) test explicitly the type of argument, it's not a Pythonic way (i really think).
