### ISSUE TITLE
Logical issue

### ISSUE THREAD

**Issue by yoyonel** [poneoneo/Alibaba-CLI-Scrapper#12]
https://github.com/poneoneo/Alibaba-CLI-Scrapper/blob/9c7c45c6cd15c79fa965931bdbc2ecd176593ada/aba_cli_scrapper/scrape_from_disk.py#L65-L77

You use `Path.resolve` (for log informations) and after check explicitly the type of the argument (to be `Path`), it's not logic.

Instead of using built-in `open` you can use [`Path.open`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.open) directly

**Comment by poneoneo** [comment]
Oh that's make sense. What if I'm catching this log line in a try except block.

**Comment by yoyonel** [comment]
No i don't think it's a good idea, just suppose that the contract/API is respected and you are a valid argument (`Path` type), don't explicitly test the type in your implementation.
If you're using a `Path` object, use [`Path.open` context manager](https://docs.python.org/3/library/pathlib.html#pathlib.Path.open) too for opening a file (input I/O stream).
My advice is just to be consistent/coherent, follow the same choice/design/architecture.

**Comment by poneoneo** [comment]
i've completly forgot that is possible with Path cause i'm mainly use this to simplify path operation.
i'm currenly working on it.
