### ISSUE TITLE
Using `Optional` instead of `<something> | None`

### ISSUE THREAD

**Issue by yoyonel** [poneoneo/Alibaba-CLI-Scrapper#6]
https://github.com/poneoneo/Alibaba-CLI-Scrapper/blob/9c7c45c6cd15c79fa965931bdbc2ecd176593ada/aba_cli_scrapper/web_scrapper.py#L88

Documentation: https://docs.python.org/3/library/typing.html#typing.Optional

**Comment by poneoneo** [comment]
Ok that make sense since I'm using typing  module

**Comment by poneoneo** [comment]
Thank you your review its will be use full to improve the code. By the way did you test it. It's work for you ?

**Comment by yoyonel** [comment]
No need really to test it, typing is purely optional in Python ^^
Don't forgot to import with `from typing import Optional` and you good to go ^^

**Comment by poneoneo** [comment]
thank you for all your reviews i really appreciate it. i will clause  some issues since they have been already implemented.
