### ISSUE TITLE
Using isort

### ISSUE THREAD

**Issue by yoyonel** [poneoneo/Alibaba-CLI-Scrapper#7]
https://github.com/poneoneo/Alibaba-CLI-Scrapper/blob/9c7c45c6cd15c79fa965931bdbc2ecd176593ada/aba_cli_scrapper/app.py#L3-L24

You can use third party tool like [`isort`](https://pycqa.github.io/isort/) for normalize yours imports in your source repo.

**Comment by poneoneo** [comment]
I forgot to run ruff to fix stuff like that I must to configure a CI but I dont know how to do it I will learn in build one on branch main for each push on

**Comment by yoyonel** [comment]
Yes very good idea to trig on a CI like [Github Action for Python project/application](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python)
If you need help, just tell me (i like this kind of stuff :p)

**Comment by poneoneo** [comment]
so maybe you could make a pr for that this could really help me. I'm also finding a way to automate publishing my package to pypi after each push on remote main branch
