### ISSUE TITLE
Refactoring: boolean evaluation

### ISSUE THREAD

**Issue by yoyonel** [poneoneo/Alibaba-CLI-Scrapper#8]
https://github.com/poneoneo/Alibaba-CLI-Scrapper/blob/9c7c45c6cd15c79fa965931bdbc2ecd176593ada/aba_cli_scrapper/app.py#L35

`if <something> is True:` <=> `if something:`

**Comment by poneoneo** [comment]
i'm planning to remove this file it will no longer be available. main code is now in __main__.py file. and for yur suggestion some time im telling me that is more readable.
