### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by yoyonel** [poneoneo/Alibaba-CLI-Scrapper#9]
https://github.com/poneoneo/Alibaba-CLI-Scrapper/blob/9c7c45c6cd15c79fa965931bdbc2ecd176593ada/aba_cli_scrapper/engine_and_database.py#L16-L21

maybe something more explicit/readable/direct:
```python
 def create_db_engine(db_name: str = "", db_url: str = ""): 
     db_url = db_url if db_url else f"sqlite:///{db_name}.sqlite"
     return create_engine(db_url) 
```

**Comment by poneoneo** [comment]
In fact it's look more readable and direct
